### ISSUE TITLE
Fake Sisaxis PS3 Controller support

### ISSUE THREAD

**Issue by digitalLumberjack** [falkTX/qtsixa#4]
Hi,
I have tried to connect an asian fake sisaxis but when i have to press Home button i have to following messages : 

``` shell
sudo sixad/sixad --start
sixad-bin[3168]: started
sixad-bin[3168]: sixad started, press the PS button now
sixad-bin[3168]: unable to connect to sdp session
sixad-bin[3168]: HID create error 110 (Connection timed out)
sixad-bin[3168]: unable to connect to sdp session
sixad-bin[3168]: HID create error 115 (Operation now in progress)
```

My controller stops and i have to press the reset button behind the controller in order to make it work again (the controller won't even start if i do not do that)

The model of my sisaxis is "ShanWan     PLAYSTATION(R)3 Controller"

**Comment by digitalLumberjack** [comment]
Fr information i tested https://github.com/yarick123/qtsixa/tree/feature/SHANWAN_FAKE_DS3 but i have exactly the same issue with this fork.

**Comment by falkTX** [comment]
Edit sixad/Makefile and change:
`GASIA_GAMEPAD_HACKS = true`
this will enable some hacks to make the gasia/fake sixaxis work

**Comment by digitalLumberjack** [comment]
I have two types of asian fake gamepads. Asia works when i compile with GASIA_GAMEPAD_HACKS = true but shanwan only works with the SHANWAN_FAKE_PS3 feature of yarick : https://github.com/yarick123/qtsixa/tree/feature/SHANWAN_FAKE_DS3

I'm working on a way to differentiate the three types of controllers at runtime in order to make sixad compatible with all of them, with the same instance running. 

Do you think it worth it ?

**Comment by falkTX** [comment]
The latest linux kernels provide official support for PS3 and PS4 joysticks/sixaxis/etc, qtsixa is no longer needed.

**Comment by digitalLumberjack** [comment]
Ok thank you for your answer.

**Comment by digitalLumberjack** [comment]
Sadly neither Asian nor Shanwan fake controllers are supported by the last bluez version. Official sixaxis works well then. 

I'll be stuck with sixad and sixpair for now. I'll try to figure how to make sixad-sixpair work with all controllers. Bye

**Comment by KonstantinKostyuk** [comment]
> The latest linux kernels provide official support for PS3 and PS4 joysticks/sixaxis/etc, qtsixa is no longer needed.

Sorry, do you have any information how it work? Or do you have any links? I dont found no one.

**Comment by falkTX** [comment]
Just plug via usb and it works, rumble, leds etc.
To make it work via bluetooth you need bluez 5.

**Comment by KonstantinKostyuk** [comment]
> To make it work via bluetooth you need bluez 5.

Install bluez 5.29, try to pair BT dongle and gamepad. Unsucces - Failed to pair: org.bluez.Error.AuthenticationTimeout

linaro@linaro-alip:~$ bluetoothctl
[NEW] Controller 00:15:83:11:2F:68 linaro-alip-0 [default]
[NEW] Device 00:16:FE:71:DD:EB 00-16-FE-71-DD-EB
[CHG] Device 00:16:FE:71:DD:EB Connected: yes
[00-16-FE-71-DD-EB]# agent on
Agent registered
[00-16-FE-71-DD-EB]# pair 00:16:FE:71:DD:EB
Attempting to pair with 00:16:FE:71:DD:EB
Request PIN code
[agent] Enter PIN code: 0000
Failed to pair: org.bluez.Error.AuthenticationTimeout

**Comment by lollo78** [comment]
Hi falkTX, I'm using Openelec 5.0.7 on a Raspberry Pi 2 (bluez version 5.29).
The original PS3 controller works like a charms with Bluetooth.
The fake "Gasia Co.,Ltd PS(R) Gamepad" fails to pair.
There is a way to patch/hack bluez to make it working?
Thx a lot!

**Comment by luetzel** [comment]
Howdy,
any progress on this issue? I've seen that some patches were discussed here:
http://article.gmane.org/gmane.linux.bluez.kernel/61352/match=sixaxis
Patches seem to work according to lozbrown85:
http://forum.kodi.tv/showthread.php?tid=222821&page=2
But they are not committed to the blueZ mainline.
Any ideas how to extract the patch from the mailinglist?
